//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSourceExam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeSourceExam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;child-row{ROWID}&quot; style=&quot;display: none;&quot;&gt;  
        ///	&lt;td&gt;&lt;/td&gt;
        ///        &lt;td&gt;{COUNTRY}&lt;/td&gt;  
        ///        &lt;td&gt;{AMOUNT}&lt;/td&gt;  
        ///&lt;/tr&gt;  .
        /// </summary>
        public static string Hidden {
            get {
                return ResourceManager.GetString("Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///table { 
        ///	width: 750px; 
        ///	border-collapse: collapse; 
        ///	margin:50px auto;
        ///	}
        ///th { 
        ///	background: #3498db; 
        ///	color: white; 
        ///	font-weight: bold; 
        ///	}
        ///td, th { 
        ///	padding: 10px; 
        ///	border: 1px solid #ccc; 
        ///	text-align: left; 
        ///	font-size: 18px;
        ///	}
        ///
        ///.labels tr td {
        ///	background-color: #2cc16a;
        ///	font-weight: bold;
        ///	color: #fff;
        ///}
        ///
        ///.label tr td label {
        ///	display: block;
        ///}
        ///
        ///
        ///[data-toggle=&quot;toggle&quot;] {
        ///	display: none;
        ///}
        ///&lt;/style&gt;
        ///
        ///&lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/jqu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr class=&quot;parent&quot; id=&quot;row{ROWID}&quot; title=&quot;Click to expand/collapse&quot; style=&quot;cursor: pointer;color:white;background-color:green;&quot; &gt;  
        ///	        &lt;td colspan=2&gt;{COUNTRYGROUP}&lt;/td&gt;  
        ///	        &lt;td&gt;{AMOUNT}&lt;/td&gt;  
        ///&lt;/tr&gt;  .
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
    }
}
